### ISSUE TITLE
大佬能否将自动更新tracker 功能加进去

### ISSUE THREAD

**Issue by Christkit** [sbwml/ariang-nginx#1]
大佬能否将自动更新tracker 功能加进去，另外在lean 固件上一直提示收集信息中，但插件使用没问题

**Comment by sbwml** [comment]
这插件不是我开发的。

这个插件它来自 openwrt 官方 feeds，因为它默认在 openwrt 22.03 的 nginx 上有点问题（至于现在官方有没有修复不清楚），我单独拿出来只是方便在我自己的固件上运行，因为我自己的固件默认使用 nginx web引擎。
